### ISSUE TITLE
Possible way to achieve "task local storage"? 

### ISSUE THREAD

**Issue by thisiscam** [utwente-fmt/lace#1]
Hi, I've probably flooded both lace and sylvan's repo recently.. but I need another help on lace.

Is it possible to achieve "task local storage" in lace? For instance, I'd like to spawn lace jobs, and be able to get a "static" variable by doing something like "current_worker->current_task->static_payload"

This will really help as sometimes passing parameters between recursive call is just not possible(for instance when I use spawn and call into a library, which than calls back on me). This will really help especially in my c# fork of sylvan, where I can now express spawn/sync with "parallel for" idioms to achieve really good dynamic parallelisms, but lacking a task local storage to make it useful in my application!

Just one or two pointers will be very helpful if you think it's possible, I can do a pull request once finished. I've looked into Task struct which contains a "d" field used for parameters; though it seems like the current Task struct is different from __lace_dq_head so I have no way of accessing it.

**Comment by trolando** [comment]
What do you mean with Task local storage. Is it like a global variable?

Why can't you accomplish this using global variables? Or using static local variables that I think C supports?

With some imagination I could rephrase the question as: I want to be able to access certain data of the last task of the current worker/thread. I can imagine that you could use thread-local storage to store data and accomplish this; especially since that task "knows" that the data is going to be required later on after the library interface.

Adding stuff to the Task data structure will have a definite impact on performance, especially if you are going to write to your "own" Task data structure, which may reside on another thread's program stack...
